import storyImage2 from '../story-photos/storyImage2.png';
import storyImage3 from '../story-photos/storyImage3.png';

const collection8 = {
  name: 'Steve and Colleen Avey',
  id: 'steveandcolleenavey',
  href: '#steveandcolleenavey',
  images: [
    null,
    null,
    null,
    null,
    null,
    null,
    storyImage3,
    null,
    null,
    storyImage2,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  stories: [
    'The first Christmas dinner Sherrie invited us over with our family to share your Christmas meal, little did she know we were so broke we were planning on having pancakes for Christmas dinner! That started off our 44-year friendship! We were so grateful for your hospitality and love.',
    'I loved serving with you in the Deacon\'s quorum. I was still young in the Churchy and you taught me a lot about scouting and teaching young men. I will never forget that incredible Deacons Quorum we had! Those were great young men that have become great men and leaders themselves.',
    'It wasn\'t just your example as a Scout Master, over the years we have watched you and marvel at what a great home teacher and ministering brother you have been. You served valiantly in the bishopric and you have touched the lives of so many people with your kind service!',
    'Our trips to Flaming Gorge and running the Green River. You took me out there for my first trip with the Deacons. I had never run a river before, but you showed me the ropes. There were other trips after that with our families, and although we came close to drowning a couple of our kids, we never lost a one. Those are great memories!',
    'I loved playing basketball with you. I learned how to be an unselfish player. You were always dishing the ball off to someone else to score! I was not very good at it, but I loved playing on our ward team with you!',
    'After we left Sandy to pursue jobs in Arizona and Virginia, you and Sherrie kept our friendship alive. Very few of our friends in Sandy ever came to visit us, but you and Sherry did, no matter where we lived!',
    'We only had two family friends come out to visit us in Virginia. You and Sherrie came right after 9/11 and we almost had the place to ourselves. You even took a trip up to Tania and Scott\'s home with us through Gettysburg and we had a great time. Sherrie was then in a wheel chair, but that did not stop either of you. Off we went all over the entire mall and beyond in Washington DC! What a fun time that was for us.',
    'Playing games together in your home is a favorite memory of ours. That continued even after we left Sandy, when we came back for visits. Those game nights were loud and fun! You always treated us like family and made us feel your home was our home!',
    'You and Sherrie came to every one of our kid\'s weddings, no matter where their weddings took place. That was so kind on Seth\'s day in Washington state and Tate\'s day in Arizona! That was really going the extra mile and truly made us feel like we were your special adopted family! That meant so much to us and our sons!',
    'Speaking of adopted family, I remember when Silver Mesa decided to have Grandparents Day. I was heartsick because my children didn\'t have a grandparent close by to come. Seth quickly asked if he could ask Sherrie to go with him. I was very worried she would be offended because she was not old enough to be his grandparent! When I asked Sherrie, she was thrilled. When Tate came along, she was \'Grandma Sherrie\'. Then when Steve\'s father passed away, we were walking down the mall with Carmen and Tate said, “I feel bad, I have 3 grandmas and no grandpas,” Carmen asked who his grandmas were and he listed Grandma Sloan, Grandma Avey and Grandma Sherrie. Carmen said, “If Grandma Sherrie is your grandma, why isn\'t Scott your grandpa?” Tate stopped dead in his tracks and his face lit up the whole mall as he said, “I do still have a grandpa, I\'ve got Grandpa Scott!”',
    'I bet you never expected to have another young adult living in your home after your kids were all married, but when we moved to Arizona right after Seth graduated from high school and lived at our home until it sold you and Sherrie watched out for him and he spent a lot of time in your home. Then after his mission your home became his home for many, many months. You blessed his life so very much during that critical time in his life!',
    'We remember well when you and Sherrie came down to visit us when I had cancer in 2005. I remember how concerned you were about me. I thought when you left our home in Arizona, that would be the last time I would get to see you. Little did I know the Lord had other plans for me!',
    'It was so wonderful and touching to see you take care of Sherrie all of the years she was so sick. We don\'t know how often you had to haul her wheel chair and later her motorized scooter with you! We worried that all of the lifting you had to do was going to do you in, especially with your hernias. You were a wonderful example of a loving husband who was being asked to carry a very heavy load.',
    'We marveled at your courage when Sherrie passed away and you had to be strong for your family when you were hurting so much yourself. What a great example you are with your faith!',
    'Your gardening has always been unbelievable! It must have been that farmer\'s blood in you, but while we could never keep our grow boxes producing, you always managed to get more fruits and vegetables than anyone we know about, then share your extra harvest with all around you! You have a very green thumb!',
    'We have always marveled at your work ethic. When you worked full-time as a school teacher, you also worked part-time jobs to keep your family afloat. Summers were not for playing, they were to work more hours at Cover Pool!',
    'The love you have always shown for your family was a great example to me. I was raised in a home with a lot of yelling and crying. We never saw you once lose your temper or get upset. That was a standard, I tried to emulate without near the success you have had!',
    'If there was ever a question of how good you and Sherry were as parents, all you have to do is look at your children. They all are good citizens, hard workers and great parents themselves. Then there is your pride and love for your grandchildren. We can feel that pride whenever you talk about any of them!',
  ],
};

export default collection8;
